### ISSUE TITLE
[quality]: Make the `destination_dir` trailing slash optional

### ISSUE THREAD

**Issue by kittaakos** [shallwefootball/upload-s3-action#11]
```yaml
- uses: shallwefootball/s3-upload-action@master
  with:
    aws_key_id: ${{ secrets.AWS_KEY_ID }}
    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    aws_bucket: ${{ secrets.AWS_BUCKET }}
    source_dir: path/to/source/
    destination_dir: path/to/dest
```

The above config generates the following upload location URL for my `my_file.zip`: `https://***.s3.amazonaws.com/path/to/destmy_file.zip` which is very wrong.

It would be great if this action could handle this gracefully, and append the trailing slash.
