### ISSUE TITLE
Error for a an upload with many files

### ISSUE THREAD

**Issue by kvz** [shallwefootball/upload-s3-action#19]
![image](https://user-images.githubusercontent.com/26752/91022741-ed58f600-e5f5-11ea-88e7-bc4e1143d362.png)

**Comment by kittaakos** [comment]
I do not know if my error is related or not, but I cannot upload artifacts from a directory:
```
##[error]AccessDenied: Access Denied
/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:6786
            throw err;
            ^

Error [TypeError]: Cannot read property 'Key' of undefined
    at ManagedUpload.callback (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:2459:36)
    at Response.finishSinglePart (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:20929:28)
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:7124:18)
    at Request.callListeners (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:11458:20)
    at Request.emit (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:11430:10)
    at Request.emit (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:7443:14)
    at Request.transition (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:6777:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:14564:12)
    at /home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:14576:10
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.2/dist/index.js:6793:9) {
  message: "Cannot read property 'Key' of undefined",
  code: 'TypeError',
  time: 2020-08-24T13:08:10.240Z
```

Version: `v1.1.2`

**Comment by kvz** [comment]
Was able to workaround this via:

```yaml
      - name: Upload to S3
        run: |
          aws s3 sync --region us-east-1 --acl public-read ./_site/ s3://site.transloadit.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        
```
