### ISSUE TITLE
Cannot read property 'Key' of undefined

### ISSUE THREAD

**Issue by slorber** [shallwefootball/upload-s3-action#27]
I have the following:

```yml

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "thread2video"
          source_dir: 'video/src'
          destination_dir: 'videos/video${{ github.run_id }}${{ github.run_number }}'
```

And get the following error:

```
Run shallwefootball/s3-upload-action@master
  with:
    aws_key_id: ***
    aws_secret_access_key: ***
  
    aws_bucket: thread2video
    source_dir: video/src
    destination_dir: videos/video67933283030
Error: AccessDenied: Access Denied
/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:6786
            throw err;
            ^

Error [TypeError]: Cannot read property 'Key' of undefined
    at ManagedUpload.callback (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:2459:36)
    at Response.finishSinglePart (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:20929:28)
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:7124:18)
    at Request.callListeners (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:11458:20)
    at Request.emit (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:11430:10)
    at Request.emit (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:7443:14)
    at Request.transition (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:6777:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:14564:12)
    at /home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:14576:10
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:6793:9) {
  message: "Cannot read property 'Key' of undefined",
  code: 'TypeError',
  time: 2021-03-23T11:05:27.014Z
}
```

It is not 100% clear why, wonder if it's not related to this code?

![image](https://user-images.githubusercontent.com/749374/112137979-3e06f080-8bd1-11eb-842b-9daf9c60d41c.png)

**Comment by JavierMonton** [comment]
I'm having the same issue right now. 
There is another [issue open](https://github.com/shallwefootball/upload-s3-action/issues/26) that says that `region` is needed to solve this, but I think there isn't an option to specify the region.

**Comment by drpym** [comment]
@JavierMonton i just saw this. You're correct this module doesn't allow for region. I may have time create a PR this weekend.

**Comment by JavierMonton** [comment]
Hi @drpym, thanks for you comment!

I think the error could be related to permissions too, in my case I found out that I had permissions for `aws cp` but not for `aws sync` and a lot of GH Actions were failing for me.
I've forked the repository and tried to add manually the region (just to test it) but it was still failing. Finally, I ended up doing it manually (installing AWS Cli and using `aws cp`) and it worked fine.

**Comment by hananmalka** [comment]
Hi, 
Any news about this issue?
I'm having the same error and couldn't find for a solution

**Comment by drpym** [comment]
The PR is open, but you can use the Aws cli as it is preinstalled in actions. Make sure to pass AWS_REGION.

**Comment by ankur0101** [comment]
> Hi @drpym, thanks for you comment!
> 
> I think the error could be related to permissions too, in my case I found out that I had permissions for `aws cp` but not for `aws sync` and a lot of GH Actions were failing for me. I've forked the repository and tried to add manually the region (just to test it) but it was still failing. Finally, I ended up doing it manually (installing AWS Cli and using `aws cp`) and it worked fine.

I had the same error. How I fixed? - Created a bucket specific policy and attached to a user and this error vanished but the new one came forward.

**Comment by panbanda** [comment]
Yeah definitely don't need the public access-- For my GH hosted runners I usually use 

```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3
        run: aws s3 sync --delete ./dist s3://...
```

But when dealing with my self hosted runners I usually have to do something different if I don't have access to the AWS CLI on the container running it.
